# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3593388a9fb287fe48b8ace3aca4b5a8e343a0e269b494bf0bb0b5ad347f99eae25e54e0d78a498ecef453f86ea806fc52c7e37da48c449a61adc9d53a2e79d

test:
  secret_key_base: fed5d1ccf0ae86cb247afb6fa490b09060304da746b75e967f588bed0a36ef1aaccce17c9c5e6b9239c0d1256189a925bdad80e20eabeac12b7a0f44ed814951

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
